use_default_settings: true

search:
  formats:
    - html
    - json
    - csv

server:
  limiter: false
  image_proxy: false
  public_instance: false

engines:
  - name: duckduckgo images
    disabled: true
  - name: deviantart
    disabled: true
  - name: pexels
    disabled: true
  - name: unsplash
    disabled: true
